### ISSUE TITLE
If one execution is missed, the sequential run will never happens, because "next_run_date" is less than 'datetime.now()'

### ISSUE THREAD

**Issue by WesleyBlancoYuan** [jarekwg/django-apscheduler#19]
Hi, one question. I have posted another similar bug, is when MySQL loses connection, but actually there ready to work, DjangoJobStore will try to reconnect, and all works fine.

But now imagine, that the MySQL is really gone. Then, when trying to reconnect, it sees the MySQL is not there and exception. Then, APScheduler will not execute the job, and thus no update to "next_run_date" of the job. 

Exception:

```
WARNING:django_apscheduler:Mysql closed the connection. Perform reconnect...
ERROR:root:
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/django_apscheduler/jobstores.py", line 64, in get_due_jobs
    out = self._get_jobs(next_run_time__lte=serialize_dt(now))
  File "/usr/lib/python2.7/site-packages/django_apscheduler/jobstores.py", line 142, in _get_jobs
    for job_id, job_state in job_states:
  File "/usr/lib64/python2.7/site-packages/django/db/models/query.py", line 250, in __iter__
    self._fetch_all()
  File "/usr/lib64/python2.7/site-packages/django/db/models/query.py", line 1118, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "/usr/lib64/python2.7/site-packages/django/db/models/query.py", line 122, in __iter__
    for row in compiler.results_iter():
  File "/usr/lib64/python2.7/site-packages/django/db/models/sql/compiler.py", line 828, in results_iter
    results = self.execute_sql(MULTI)
  File "/usr/lib64/python2.7/site-packages/django/db/models/sql/compiler.py", line 874, in execute_sql
    cursor = self.connection.cursor()
  File "/usr/lib64/python2.7/site-packages/django/db/backends/base/base.py", line 254, in cursor
    return self._cursor()
  File "/usr/lib64/python2.7/site-packages/django/db/backends/base/base.py", line 229, in _cursor
    self.ensure_connection()
  File "/usr/lib64/python2.7/site-packages/django/db/backends/base/base.py", line 213, in ensure_connection
    self.connect()
  File "/usr/lib64/python2.7/site-packages/django/db/utils.py", line 94, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/usr/lib64/python2.7/site-packages/django/db/backends/base/base.py", line 213, in ensure_connection
    self.connect()
  File "/usr/lib64/python2.7/site-packages/django/db/backends/base/base.py", line 189, in connect
    self.connection = self.get_new_connection(conn_params)
  File "/usr/lib64/python2.7/site-packages/django/db/backends/mysql/base.py", line 274, in get_new_connection
    conn = Database.connect(**conn_params)
  File "/usr/lib64/python2.7/site-packages/MySQLdb/__init__.py", line 81, in Connect
    return Connection(*args, **kwargs)
  File "/usr/lib64/python2.7/site-packages/MySQLdb/connections.py", line 193, in __init__
    super(Connection, self).__init__(*args, **kwargs2)
OperationalError: (2002, "Can't connect to local MySQL server through socket '/var/lib/mysql/mysql.sock' (2)")
Exception in thread APScheduler:
Traceback (most recent call last):
  File "/usr/lib64/python2.7/threading.py", line 812, in __bootstrap_inner
    self.run()
  File "/usr/lib64/python2.7/threading.py", line 765, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/usr/lib64/python2.7/site-packages/apscheduler/schedulers/blocking.py", line 30, in _main_loop
    wait_seconds = self._process_jobs()
  File "/usr/lib64/python2.7/site-packages/apscheduler/schedulers/base.py", line 945, in _process_jobs
    for job in due_jobs:
TypeError: 'NoneType' object is not iterable
```

Then, after some time, we find the problem and restart MySQL. Now, in the table of `django_apscheduler_djangojob`, `next_run_time` will be some moment ago, and, missed forever, because it is earlier than now. Then, the job has the state of `running` in the APScheduler, the APScheduler is running too, but this job enters a state of "zombie".

I think, we must take this into consideration, right?

I am not saying that it is very possible(the db fails when the machine still runs). It is a very particular corner case.

**Comment by sallyruthstruik** [comment]
Hello. Thank you for detail explanation of problem. I'll try to reproduce this case, and will research the problem. Zombie tasks are definetely a bug.

**Comment by sallyruthstruik** [comment]
@WesleyBlancoYuan Did your restart scheduler process after starting mysql?

**Comment by sallyruthstruik** [comment]
Looks like in case of no jobs, apscheduler stops main cycle and waits "add_job" to be called: https://github.com/agronholm/apscheduler/blob/5b402ec0e8643bcad9ff37d3dfd3a849c7b1066f/apscheduler/schedulers/base.py#L913

So it means that:
* Mysql dies
* get_due_jobs returns None
* apscheduler decided that there are no jobs for execution at all and sleeps forever, waiting add_job event

Only solution I see (without changing apscheduler logic) - to provide wrapper around apscheduler, which can change this behavior. It can be little tricky, but also allows to solve this PR: #16

**Comment by WesleyBlancoYuan** [comment]
@sallyruthstruik No. I didn't start the scheduler as a separated process, that is not the proper way to use APScheduler, I know it, because Alex, the author suggests "always use it as a separate process", but that is what we are doing now. 

A temporary solution is to add a `crontab` job, to restart the scheduler via a web service module every 4 hours, which we write specially for this situation. Ugly and dirty, I know.

**Comment by sallyruthstruik** [comment]
Created PR in apscheduler repo: https://github.com/agronholm/apscheduler/issues/305 
If author will agree with such functionality I'll will fix it very easy and quickly. Otherwise it will be very cheating and ugly solution :(

**Comment by jcass77** [comment]
The upcoming v0.4.0 release changes a lot of the internal django_apscheduler logic, which I **think** will resolve this issue.

The way I see it, if your (MySQL) database dies then Django will probably fall over as well. Recovering from this situation probably involves restarting the Django server, which should ideally trigger your `scheduler.add_job()`s to be called again and resubmit the jobs to APScheduler.

Please re-open if the problem persists so that we can look at the specific circumstances of your implementation.
