### ISSUE TITLE
When I remove a job from the scheduler

### ISSUE THREAD

**Issue by hhyo** [jarekwg/django-apscheduler#20]
- env:
Django==1.8.17
django-apscheduler==0.2.7

- code:
```
job_id=test
scheduler.add_job(_execute_job, 'date', run_date=run_date, args=[workflowId, url], id=job_id,
                          replace_existing=True)
scheduler.remove_job(job_id)
```

- traceback:
```
[2018-04-28 21:44:50,884][Thread-22:123145460006912][task_id:default][exception_logging_middleware.py:10] [ERROR]- Traceback (most recent call last):
  File "/Users/lihuanhuan/PycharmProjects/venv4archer/lib/python3.6/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/lihuanhuan/PycharmProjects/archer-github/sql/views.py", line 410, in cancel
    del_sqlcronjob(job_id)
  File "/Users/lihuanhuan/PycharmProjects/archer-github/sql/jobs.py", line 53, in del_sqlcronjob
    return scheduler.remove_job(job_id)
  File "/Users/lihuanhuan/PycharmProjects/venv4archer/lib/python3.6/site-packages/apscheduler/schedulers/base.py", line 608, in remove_job
    store.remove_job(job_id)
  File "/Users/lihuanhuan/PycharmProjects/venv4archer/lib/python3.6/site-packages/django_apscheduler/jobstores.py", line 27, in inner
    return func(*a, **k)
  File "/Users/lihuanhuan/PycharmProjects/venv4archer/lib/python3.6/site-packages/django_apscheduler/jobstores.py", line 117, in remove_job
    deleted, _ = DjangoJob.objects.filter(name=job_id).delete()
TypeError: 'NoneType' object is not iterable

```
- jobstores.py", line 117
```
    @ignore_database_error
    def remove_job(self, job_id):
        deleted, _ = DjangoJob.objects.filter(name=job_id).delete() 
        if deleted == 0:
            raise JobLookupError(job_id)
```

**Comment by sallyruthstruik** [comment]
Fixed in new release: https://github.com/jarekwg/django-apscheduler/releases/tag/0.2.8

**Comment by sallyruthstruik** [comment]
please, check that everything is ok and give feedback to allow me close the issue

**Comment by hhyo** [comment]
Everything is ok!  Thanks！
