### ISSUE TITLE
How to install ?

### ISSUE THREAD

**Issue by elcolie** [jarekwg/django-apscheduler#4]
How to install ?

**Comment by jarekwg** [comment]
Hi there,

You can either
- `pip install -e git+https://github.com/jarekwg/django-apscheduler.git#egg=django_apscheduler`
- Install [this fork](https://github.com/sallyruthstruik/django-apscheduler) from PyPI, which seems to be getting more actively maintained (though I haven't used it myself): `pip install django-apscheduler`

If you are really interested in using this repo, let me know and I'll make an effort to get it up on PyPI.

Cheers,

**Comment by elcolie** [comment]
```bash
ERROR:root:
Traceback (most recent call last):
  File "/Users/el/.pyenv/versions/eneos-pos-web/lib/python3.6/site-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/Users/el/.pyenv/versions/eneos-pos-web/lib/python3.6/site-packages/opbeat/instrumentation/packages/dbapi2.py", line 169, in execute
    return self._trace_sql(self.__wrapped__.execute, sql, params)
  File "/Users/el/.pyenv/versions/eneos-pos-web/lib/python3.6/site-packages/opbeat/instrumentation/packages/dbapi2.py", line 182, in _trace_sql
    return method(sql, params)
psycopg2.ProgrammingError: relation "django_apscheduler_djangojob" does not exist
LINE 1: ..., "django_apscheduler_djangojob"."job_state" FROM "django_ap...
                                                             ^


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/el/.pyenv/versions/eneos-pos-web/lib/python3.6/site-packages/django_apscheduler/jobstores.py", line 40, in get_due_jobs
    return self._get_jobs(next_run_time__lte=serialize_dt(now))
  File "/Users/el/.pyenv/versions/eneos-pos-web/lib/python3.6/site-packages/django_apscheduler/jobstores.py", line 101, in _get_jobs
    for job_id, job_state in job_states:
  File "/Users/el/.pyenv/versions/eneos-pos-web/lib/python3.6/site-packages/django/db/models/query.py", line 256, in __iter__
    self._fetch_all()
  File "/Users/el/.pyenv/versions/eneos-pos-web/lib/python3.6/site-packages/django/db/models/query.py", line 1087, in _fetch_all
    self._result_cache = list(self.iterator())
  File "/Users/el/.pyenv/versions/eneos-pos-web/lib/python3.6/site-packages/django/db/models/query.py", line 125, in __iter__
    for row in compiler.results_iter():
  File "/Users/el/.pyenv/versions/eneos-pos-web/lib/python3.6/site-packages/django/db/models/sql/compiler.py", line 789, in results_iter
    results = self.execute_sql(MULTI)
  File "/Users/el/.pyenv/versions/eneos-pos-web/lib/python3.6/site-packages/django/db/models/sql/compiler.py", line 835, in execute_sql
    cursor.execute(sql, params)
  File "/Users/el/.pyenv/versions/eneos-pos-web/lib/python3.6/site-packages/django/db/backends/utils.py", line 79, in execute
    return super(CursorDebugWrapper, self).execute(sql, params)
  File "/Users/el/.pyenv/versions/eneos-pos-web/lib/python3.6/site-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/Users/el/.pyenv/versions/eneos-pos-web/lib/python3.6/site-packages/django/db/utils.py", line 94, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/Users/el/.pyenv/versions/eneos-pos-web/lib/python3.6/site-packages/django/utils/six.py", line 685, in reraise
    raise value.with_traceback(tb)
  File "/Users/el/.pyenv/versions/eneos-pos-web/lib/python3.6/site-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/Users/el/.pyenv/versions/eneos-pos-web/lib/python3.6/site-packages/opbeat/instrumentation/packages/dbapi2.py", line 169, in execute
    return self._trace_sql(self.__wrapped__.execute, sql, params)
  File "/Users/el/.pyenv/versions/eneos-pos-web/lib/python3.6/site-packages/opbeat/instrumentation/packages/dbapi2.py", line 182, in _trace_sql
    return method(sql, params)
django.db.utils.ProgrammingError: relation "django_apscheduler_djangojob" does not exist
LINE 1: ..., "django_apscheduler_djangojob"."job_state" FROM "django_ap...
                                                             ^

Exception in thread APScheduler:
Traceback (most recent call last):
  File "/Users/el/.pyenv/versions/3.6.0/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/Users/el/.pyenv/versions/3.6.0/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/el/.pyenv/versions/eneos-pos-web/lib/python3.6/site-packages/apscheduler/schedulers/blocking.py", line 30, in _main_loop
    wait_seconds = self._process_jobs()
  File "/Users/el/.pyenv/versions/eneos-pos-web/lib/python3.6/site-packages/apscheduler/schedulers/base.py", line 943, in _process_jobs
    for job in due_jobs:
TypeError: 'NoneType' object is not iterable
```
Any ideas?

**Comment by jarekwg** [comment]
Did you run migrations?
Also, that error looks like it's coming from the base apscheduler package, not this one.

**Comment by elcolie** [comment]
Sure. I did.

**Comment by andychoi** [comment]
The package has a problem, initial setup without app logic will create tables in database.
But if you do have app logics and try to do initial migration, it will fail like this. It is a bug in the package...
