### ISSUE TITLE
does it support async ?

### ISSUE THREAD

**Issue by boyl** [jarekwg/django-apscheduler#40]
**whether I use AsyncIOScheduler or BackgroundScheduler, when I run my django server, it just raise exception.**
**a short pic:**
![image](https://user-images.githubusercontent.com/30596191/48389341-fd148c80-e737-11e8-97b6-48875ce01d8e.png)
**a long text info :**
`Unhandled exception in thread started by <function check_errors.<locals>.wrapper at 0x0376C3D8>
Traceback (most recent call last):
  File "C:\Users\Administrator\.virtualenvs\justjoke-0zIsqtwi\lib\site-packages\django\utils\autoreload.py", line 227, in wrapper
    fn(*args, **kwargs)
  File "C:\Users\Administrator\.virtualenvs\justjoke-0zIsqtwi\lib\site-packages\django\core\management\commands\runserver.py", line 125, in inner_run
    self.check(display_num_errors=True)
  File "C:\Users\Administrator\.virtualenvs\justjoke-0zIsqtwi\lib\site-packages\django\core\management\base.py", line 359, in check
    include_deployment_checks=include_deployment_checks,
  File "C:\Users\Administrator\.virtualenvs\justjoke-0zIsqtwi\lib\site-packages\django\core\management\base.py", line 346, in _run_checks
    return checks.run_checks(**kwargs)
  File "C:\Users\Administrator\.virtualenvs\justjoke-0zIsqtwi\lib\site-packages\django\core\checks\registry.py", line 81, in run_checks
    new_errors = check(app_configs=app_configs)
  File "C:\Users\Administrator\.virtualenvs\justjoke-0zIsqtwi\lib\site-packages\django\core\checks\urls.py", line 16, in check_url_config
    return check_resolver(resolver)
  File "C:\Users\Administrator\.virtualenvs\justjoke-0zIsqtwi\lib\site-packages\django\core\checks\urls.py", line 26, in check_resolver
    return check_method()
  File "C:\Users\Administrator\.virtualenvs\justjoke-0zIsqtwi\lib\site-packages\django\urls\resolvers.py", line 254, in check
    for pattern in self.url_patterns:
  File "C:\Users\Administrator\.virtualenvs\justjoke-0zIsqtwi\lib\site-packages\django\utils\functional.py", line 35, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "C:\Users\Administrator\.virtualenvs\justjoke-0zIsqtwi\lib\site-packages\django\urls\resolvers.py", line 405, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "C:\Users\Administrator\.virtualenvs\justjoke-0zIsqtwi\lib\site-packages\django\utils\functional.py", line 35, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "C:\Users\Administrator\.virtualenvs\justjoke-0zIsqtwi\lib\site-packages\django\urls\resolvers.py", line 398, in urlconf_module
    return import_module(self.urlconf_name)
  File "C:\Users\Administrator\.virtualenvs\justjoke-0zIsqtwi\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 986, in _gcd_import
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 673, in exec_module
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "F:\works\study\WorkSpace\justjoke\AJoke\AJoke\urls.py", line 48, in <module>
    import records.interfaceprocess
  File "F:\works\study\WorkSpace\justjoke\AJoke\records\interfaceprocess.py", line 76, in <module>
    main()
  File "F:\works\study\WorkSpace\justjoke\AJoke\records\interfaceprocess.py", line 71, in main
    loop = asyncio.get_event_loop()
  File "C:\python35\Lib\asyncio\events.py", line 671, in get_event_loop
    return get_event_loop_policy().get_event_loop()
  File "C:\python35\Lib\asyncio\events.py", line 583, in get_event_loop
    % threading.current_thread().name)
RuntimeError: There is no current event loop in thread 'Dummy-1'.
`

**Comment by jcass77** [comment]
django_scheduler does not have any built-in support for async, but that does not mean that you cannot use it with other async functions.

From the error above it looks like you have not started the event loop - Django 3 has been released since this issue was first posted and contain some examples and documentation that might help you get started - see: https://docs.djangoproject.com/en/3.0/topics/async/#asynchronous-support.
