### ISSUE TITLE
add_job filed: This Job cannot be serialized since the reference to its callable

### ISSUE THREAD

**Issue by Near-Zhang** [jarekwg/django-apscheduler#46]
code:
``` python
jobstores = {
    'default': DjangoJobStore()
}

scheduler = BackgroundScheduler(jobstores=jobstores, timezone=timezone('Asia/Shanghai'))
scheduler.start()

class CommandView(BaseView):

    def post(self, request):

        @register_job(scheduler, "interval", seconds=10)
        def test_job():
            print('123')

        register_events(scheduler)
        return self.base_json_response({'1': 123})
```
log:
>Traceback (most recent call last):
  File "/work/apps/task_execute/venv/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/work/apps/task_execute/venv/lib/python3.6/site-packages/django/core/handlers/base.py", line 126, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/work/apps/task_execute/venv/lib/python3.6/site-packages/django/core/handlers/base.py", line 124, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/work/apps/task_execute/venv/lib/python3.6/site-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/work/apps/task_execute/venv/lib/python3.6/site-packages/django/views/generic/base.py", line 88, in dispatch
    return handler(request, *args, **kwargs)
  File "/work/apps/task_execute/schedule/views.py", line 27, in post
    @register_job(scheduler, "interval", seconds=10)
  File "/work/apps/task_execute/venv/lib/python3.6/site-packages/django_apscheduler/jobstores.py", line 247, in inner
    scheduler.add_job(func, *a, **k)
  File "/work/apps/task_execute/venv/lib/python3.6/site-packages/apscheduler/schedulers/base.py", line 439, in add_job
    self._real_add_job(job, jobstore, replace_existing)
  File "/work/apps/task_execute/venv/lib/python3.6/site-packages/apscheduler/schedulers/base.py", line 864, in _real_add_job
    store.add_job(job)
  File "/work/apps/task_execute/venv/lib/python3.6/site-packages/django_apscheduler/jobstores.py", line 29, in inner
    return func(*a, **k)
  File "/work/apps/task_execute/venv/lib/python3.6/site-packages/django_apscheduler/jobstores.py", line 95, in add_job
    job_state=pickle.dumps(job.__getstate__(), self.pickle_protocol)
  File "/work/apps/task_execute/venv/lib/python3.6/site-packages/apscheduler/job.py", line 237, in __getstate__
    'instead.' % (self.func,))
ValueError: This Job cannot be serialized since the reference to its callable (<function CommandView.post.<locals>.test_job at 0x7f2491ef2d08>) could not be determined. Consider giving a textual reference (module:function name) instead.

**Comment by mkoertgen** [comment]
@Near-Zhang job functions must static and not be local to a class (see pickle). Workaround:

```
def my_job_func(self):
   # do your stuff


scheduler.add_job(self.my_job_func, trigger=None, ...)
```

**Comment by jcass77** [comment]
Closing based on answer provided by @mkoertgen - please re-open if necessary.
