### ISSUE TITLE
add_job 'cron' causing error in django-admin

### ISSUE THREAD

**Issue by mkomod** [jarekwg/django-apscheduler#57]
Code: 

```
import time
from apscheduler.schedulers.background import BackgroundScheduler
from django_apscheduler.jobstores import DjangoJobStore, register_events, register_job

scheduler = BackgroundScheduler()
scheduler.add_jobstore(DjangoJobStore(), "default")

def test_job(text):
    print(text)

scheduler.add_job(test_job, 'cron', year=2019, month=3, day=18, hour=18, minute=6, second=50, args=['some text'])

register_events(scheduler)
scheduler.start()
print("Scheduler started!")
```

Returns the following:

```
Internal Server Error: /admin/django_apscheduler/djangojob/
Traceback (most recent call last):
  File "...site-packages/django/db/models/options.py", line 564, in get_field
    return self.fields_map[field_name]
KeyError: 'next_run_time_sec'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "...site-packages/django/contrib/admin/utils.py", line 278, in lookup_field
    f = _get_non_gfk_field(opts, name)
  File "...site-packages/django/contrib/admin/utils.py", line 309, in _get_non_gfk_field
    field = opts.get_field(name)
  File "...site-packages/django/db/models/options.py", line 566, in get_field
    raise FieldDoesNotExist("%s has no field named '%s'" % (self.object_name, field_name))
django.core.exceptions.FieldDoesNotExist: DjangoJob has no field named 'next_run_time_sec'

During handling of the above exception, another exception occurred:


Traceback (most recent call last):
  File "...site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "...site-packages/django/core/handlers/base.py", line 156, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "...site-packages/django/core/handlers/base.py", line 154, in _get_response
    response = response.render()
  File "...site-packages/django/template/response.py", line 106, in render
    self.content = self.rendered_content
  File "...site-packages/django/template/response.py", line 83, in rendered_content
    content = template.render(context, self._request)
  File "...site-packages/django/template/backends/django.py", line 61, in render
    return self.template.render(context)
  File "...site-packages/django/template/base.py", line 171, in render
    return self._render(context)
  File "...site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
  File "...site-packages/django/template/base.py", line 937, in render
    bit = node.render_annotated(context)
  File "...site-packages/django/template/base.py", line 904, in render_annotated
    return self.render(context)
  File "...site-packages/django/template/loader_tags.py", line 150, in render
    return compiled_parent._render(context)
  File "...site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
  File "...site-packages/django/template/base.py", line 937, in render
    bit = node.render_annotated(context)
  File "...site-packages/django/template/base.py", line 904, in render_annotated
    return self.render(context)
  File "...site-packages/django/template/loader_tags.py", line 150, in render
    return compiled_parent._render(context)
  File "...site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
  File "...site-packages/django/template/base.py", line 937, in render
    bit = node.render_annotated(context)
  File "...site-packages/django/template/base.py", line 904, in render_annotated
    return self.render(context)
  File "...site-packages/django/template/loader_tags.py", line 62, in render
    result = block.nodelist.render(context)
  File "...site-packages/django/template/base.py", line 937, in render
    bit = node.render_annotated(context)
  File "...site-packages/django/template/base.py", line 904, in render_annotated
    return self.render(context)
  File "...site-packages/django/template/loader_tags.py", line 62, in render
    result = block.nodelist.render(context)
  File "...site-packages/django/template/base.py", line 937, in render
    bit = node.render_annotated(context)
  File "...site-packages/django/template/base.py", line 904, in render_annotated
    return self.render(context)
  File "...site-packages/django/contrib/admin/templatetags/base.py", line 33, in render
    return super().render(context)
  File "...site-packages/django/template/library.py", line 214, in render
    _dict = self.func(*resolved_args, **resolved_kwargs)
  File "...site-packages/django/contrib/admin/templatetags/admin_list.py", line 341, in result_list
    'results': list(results(cl))}
  File "...site-packages/django/contrib/admin/templatetags/admin_list.py", line 318, in results
    yield ResultList(None, items_for_result(cl, res, None))
  File "...site-packages/django/contrib/admin/templatetags/admin_list.py", line 309, in __init__
    super().__init__(*items)
  File "...site-packages/django/contrib/admin/templatetags/admin_list.py", line 228, in items_for_result
    f, attr, value = lookup_field(field_name, result, cl.model_admin)
  File "...site-packages/django/contrib/admin/utils.py", line 287, in lookup_field
    value = attr(obj)
  File "...site-packages/django_apscheduler/admin.py", line 35, in next_run_time_sec
    return obj.next_run_time.strftime("%Y-%m-%d %H:%M:%S")
AttributeError: 'NoneType' object has no attribute 'strftime'
```

I fixed the issue by adding the following lines to django_apscheduler/admin.py

```
    def next_run_time_sec(self, obj):
        try:
            return obj.next_run_time.strftime("%Y-%m-%d %H:%M:%S")
        except AttributeError:
            return None
```

I'm happy to submit a PR with a more suitable fix

**Comment by jcass77** [comment]
I think this was resolved some time ago using exactly the approach suggested above.

Please re-open if necessary.
